// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.3
// DateTime: 28/11/2025 12:24:07 AM
// Input file <Calculator\Calculator.Language.grammar.y - 28/11/2025 12:24:05 AM>

// options: no-lines gplex

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using Kotor.NET.Script.Compiler.AST;

namespace Kotor_NET_Script_Compiler.Calculator
{
internal enum Token {error=2,EOF=3,SEMI=4,COMMA=5,LBRACE=6,
    RBRACE=7,LPAREN=8,RPAREN=9,IDENTIFIER=10,RETURN=11,VOID_TYPE=12,
    INT_TYPE=13,FLOAT_TYPE=14,STRING_TYPE=15,BOOL_TYPE=16,VECTOR_TYPE=17,LOCATION_TYPE=18,
    EFFECT_TYPE=19,INT_LITERAL=20,FLOAT_LITERAL=21,STRING_LITERAL=22,BOOL_LITERAL=23,OBJECT_LITERAL=24};

// Abstract base class for GPLEX scanners
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.3")]
internal abstract class ScanBase : AbstractScanner<AstNode,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.3")]
internal class ScanObj {
  public int token;
  public AstNode yylval;
  public LexLocation yylloc;
  public ScanObj( int t, AstNode val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.3")]
internal partial class CalculatorParser: ShiftReduceParser<AstNode, LexLocation>
{
  // Verbatim content from Calculator\Calculator.Language.grammar.y - 28/11/2025 12:24:05 AM
public class AstNode {}
  // End verbatim content from Calculator\Calculator.Language.grammar.y - 28/11/2025 12:24:05 AM

#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[45];
  private static State[] states = new State[60];
  private static string[] nonTerms = new string[] {
      "compilation_unit", "$accept", "declaration_list", "declaration", "forward_declaration", 
      "complete_declaration", "function_signature", "statement_list", "type_specifier", 
      "parameter_list", "parameter_declaration", "statement", "declaration_statement", 
      "return_statement", "expression", "variable_declarators", "initialisation_statement", 
      "constant_expression", "function_call_expression", "argument_list", };

  static CalculatorParser() {
    states[0] = new State(new int[]{12,20,13,21,14,22,15,23,17,24,18,25,19,26,3,-5},new int[]{-1,1,-3,3,-4,59,-5,5,-7,6,-9,48,-6,58});
    states[1] = new State(new int[]{3,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{12,20,13,21,14,22,15,23,17,24,18,25,19,26,3,-2},new int[]{-4,4,-5,5,-7,6,-9,48,-6,58});
    states[4] = new State(-4);
    states[5] = new State(-6);
    states[6] = new State(new int[]{4,7,6,8});
    states[7] = new State(-9);
    states[8] = new State(new int[]{4,12,12,20,13,21,14,22,15,23,17,24,18,25,19,26,11,28,20,33,21,34,22,35,24,36,23,37,10,39,7,-24},new int[]{-8,9,-12,47,-13,13,-9,14,-14,27,-15,45,-18,32,-19,38});
    states[9] = new State(new int[]{7,10,4,12,12,20,13,21,14,22,15,23,17,24,18,25,19,26,11,28,20,33,21,34,22,35,24,36,23,37,10,39},new int[]{-12,11,-13,13,-9,14,-14,27,-15,45,-18,32,-19,38});
    states[10] = new State(-8);
    states[11] = new State(-23);
    states[12] = new State(-25);
    states[13] = new State(-26);
    states[14] = new State(new int[]{10,19},new int[]{-16,15});
    states[15] = new State(new int[]{4,16,5,17});
    states[16] = new State(-29);
    states[17] = new State(new int[]{10,18});
    states[18] = new State(-33);
    states[19] = new State(-32);
    states[20] = new State(-15);
    states[21] = new State(-16);
    states[22] = new State(-17);
    states[23] = new State(-18);
    states[24] = new State(-19);
    states[25] = new State(-20);
    states[26] = new State(-21);
    states[27] = new State(-27);
    states[28] = new State(new int[]{4,29,20,33,21,34,22,35,24,36,23,37,10,39},new int[]{-15,30,-18,32,-19,38});
    states[29] = new State(-30);
    states[30] = new State(new int[]{4,31});
    states[31] = new State(-31);
    states[32] = new State(-35);
    states[33] = new State(-37);
    states[34] = new State(-38);
    states[35] = new State(-39);
    states[36] = new State(-40);
    states[37] = new State(-41);
    states[38] = new State(-36);
    states[39] = new State(new int[]{8,40});
    states[40] = new State(new int[]{20,33,21,34,22,35,24,36,23,37,10,39},new int[]{-20,41,-15,44,-18,32,-19,38});
    states[41] = new State(new int[]{9,42,20,33,21,34,22,35,24,36,23,37,10,39},new int[]{-15,43,-18,32,-19,38});
    states[42] = new State(-42);
    states[43] = new State(-44);
    states[44] = new State(-43);
    states[45] = new State(new int[]{4,46});
    states[46] = new State(-28);
    states[47] = new State(-22);
    states[48] = new State(new int[]{10,49});
    states[49] = new State(new int[]{8,50});
    states[50] = new State(new int[]{12,20,13,21,14,22,15,23,17,24,18,25,19,26,9,-13,5,-13},new int[]{-10,51,-11,57,-9,55});
    states[51] = new State(new int[]{9,52,5,53});
    states[52] = new State(-10);
    states[53] = new State(new int[]{12,20,13,21,14,22,15,23,17,24,18,25,19,26},new int[]{-11,54,-9,55});
    states[54] = new State(-12);
    states[55] = new State(new int[]{10,56});
    states[56] = new State(-14);
    states[57] = new State(-11);
    states[58] = new State(-7);
    states[59] = new State(-3);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-2, new int[]{-1,3});
    rules[2] = new Rule(-1, new int[]{-3});
    rules[3] = new Rule(-3, new int[]{-4});
    rules[4] = new Rule(-3, new int[]{-3,-4});
    rules[5] = new Rule(-3, new int[]{});
    rules[6] = new Rule(-4, new int[]{-5});
    rules[7] = new Rule(-4, new int[]{-6});
    rules[8] = new Rule(-6, new int[]{-7,6,-8,7});
    rules[9] = new Rule(-5, new int[]{-7,4});
    rules[10] = new Rule(-7, new int[]{-9,10,8,-10,9});
    rules[11] = new Rule(-10, new int[]{-11});
    rules[12] = new Rule(-10, new int[]{-10,5,-11});
    rules[13] = new Rule(-10, new int[]{});
    rules[14] = new Rule(-11, new int[]{-9,10});
    rules[15] = new Rule(-9, new int[]{12});
    rules[16] = new Rule(-9, new int[]{13});
    rules[17] = new Rule(-9, new int[]{14});
    rules[18] = new Rule(-9, new int[]{15});
    rules[19] = new Rule(-9, new int[]{17});
    rules[20] = new Rule(-9, new int[]{18});
    rules[21] = new Rule(-9, new int[]{19});
    rules[22] = new Rule(-8, new int[]{-12});
    rules[23] = new Rule(-8, new int[]{-8,-12});
    rules[24] = new Rule(-8, new int[]{});
    rules[25] = new Rule(-12, new int[]{4});
    rules[26] = new Rule(-12, new int[]{-13});
    rules[27] = new Rule(-12, new int[]{-14});
    rules[28] = new Rule(-12, new int[]{-15,4});
    rules[29] = new Rule(-13, new int[]{-9,-16,4});
    rules[30] = new Rule(-14, new int[]{11,4});
    rules[31] = new Rule(-14, new int[]{11,-15,4});
    rules[32] = new Rule(-16, new int[]{10});
    rules[33] = new Rule(-16, new int[]{-16,5,10});
    rules[34] = new Rule(-17, new int[]{-9,10});
    rules[35] = new Rule(-15, new int[]{-18});
    rules[36] = new Rule(-15, new int[]{-19});
    rules[37] = new Rule(-18, new int[]{20});
    rules[38] = new Rule(-18, new int[]{21});
    rules[39] = new Rule(-18, new int[]{22});
    rules[40] = new Rule(-18, new int[]{24});
    rules[41] = new Rule(-18, new int[]{23});
    rules[42] = new Rule(-19, new int[]{10,8,-20,9});
    rules[43] = new Rule(-20, new int[]{-15});
    rules[44] = new Rule(-20, new int[]{-20,-15});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Token.error, (int)Token.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 2: // compilation_unit -> declaration_list
{ CurrentSemanticValue = new AstNode(); }
        break;
      case 4: // declaration_list -> declaration_list, declaration
{ }
        break;
      case 5: // declaration_list -> /* empty */
{ }
        break;
      case 6: // declaration -> forward_declaration
{ Console.WriteLine("Hello World"); }
        break;
      case 7: // declaration -> complete_declaration
{ }
        break;
      case 8: // complete_declaration -> function_signature, LBRACE, statement_list, RBRACE
{ }
        break;
      case 9: // forward_declaration -> function_signature, SEMI
{ }
        break;
      case 10: // function_signature -> type_specifier, IDENTIFIER, LPAREN, parameter_list, 
               //                       RPAREN
{ }
        break;
      case 11: // parameter_list -> parameter_declaration
{ }
        break;
      case 12: // parameter_list -> parameter_list, COMMA, parameter_declaration
{ }
        break;
      case 13: // parameter_list -> /* empty */
{ }
        break;
      case 14: // parameter_declaration -> type_specifier, IDENTIFIER
{ }
        break;
      case 15: // type_specifier -> VOID_TYPE
{ }
        break;
      case 16: // type_specifier -> INT_TYPE
{ }
        break;
      case 17: // type_specifier -> FLOAT_TYPE
{ }
        break;
      case 18: // type_specifier -> STRING_TYPE
{ }
        break;
      case 19: // type_specifier -> VECTOR_TYPE
{ }
        break;
      case 20: // type_specifier -> LOCATION_TYPE
{ }
        break;
      case 21: // type_specifier -> EFFECT_TYPE
{ }
        break;
      case 22: // statement_list -> statement
{ }
        break;
      case 23: // statement_list -> statement_list, statement
{ }
        break;
      case 24: // statement_list -> /* empty */
{ }
        break;
      case 25: // statement -> SEMI
{ }
        break;
      case 26: // statement -> declaration_statement
{ }
        break;
      case 27: // statement -> return_statement
{ }
        break;
      case 28: // statement -> expression, SEMI
{ }
        break;
      case 29: // declaration_statement -> type_specifier, variable_declarators, SEMI
{ }
        break;
      case 30: // return_statement -> RETURN, SEMI
{ }
        break;
      case 31: // return_statement -> RETURN, expression, SEMI
{ }
        break;
      case 32: // variable_declarators -> IDENTIFIER
{ }
        break;
      case 33: // variable_declarators -> variable_declarators, COMMA, IDENTIFIER
{ }
        break;
      case 35: // expression -> constant_expression
{ }
        break;
      case 36: // expression -> function_call_expression
{ }
        break;
      case 37: // constant_expression -> INT_LITERAL
{ }
        break;
      case 38: // constant_expression -> FLOAT_LITERAL
{ }
        break;
      case 39: // constant_expression -> STRING_LITERAL
{ }
        break;
      case 40: // constant_expression -> OBJECT_LITERAL
{ }
        break;
      case 41: // constant_expression -> BOOL_LITERAL
{ }
        break;
      case 43: // argument_list -> expression
{ }
        break;
      case 44: // argument_list -> argument_list, expression
{ }
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((Token)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Token)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

}
}
