//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/hugin/source/repos/Kotor.NET/Kotor.NET.PatchingLanguage/KotorPatchingLanguage.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="KotorPatchingLanguageParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IKotorPatchingLanguageVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="KotorPatchingLanguageParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScript([NotNull] KotorPatchingLanguageParser.ScriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KotorPatchingLanguageParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction([NotNull] KotorPatchingLanguageParser.InstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>File_Operation_Create</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.file_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_Operation_Create([NotNull] KotorPatchingLanguageParser.File_Operation_CreateContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>File_Operation_Modify</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.file_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_Operation_Modify([NotNull] KotorPatchingLanguageParser.File_Operation_ModifyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>File_Operation_CreateOrReplace</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.file_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_Operation_CreateOrReplace([NotNull] KotorPatchingLanguageParser.File_Operation_CreateOrReplaceContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>File_Operation_CreateOrModify</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.file_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_Operation_CreateOrModify([NotNull] KotorPatchingLanguageParser.File_Operation_CreateOrModifyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>File_Source_Key</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.file_source"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_Source_Key([NotNull] KotorPatchingLanguageParser.File_Source_KeyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>File_Source_Module</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.file_source"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_Source_Module([NotNull] KotorPatchingLanguageParser.File_Source_ModuleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>File_Source_Override</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.file_source"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_Source_Override([NotNull] KotorPatchingLanguageParser.File_Source_OverrideContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>File_Target_Module</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.file_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_Target_Module([NotNull] KotorPatchingLanguageParser.File_Target_ModuleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>File_Target_Override</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.file_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_Target_Override([NotNull] KotorPatchingLanguageParser.File_Target_OverrideContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CopyFiles</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.copy_files"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCopyFiles([NotNull] KotorPatchingLanguageParser.CopyFilesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Copy_Files_Target_Module</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.copy_files_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCopy_Files_Target_Module([NotNull] KotorPatchingLanguageParser.Copy_Files_Target_ModuleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Copy_Files_Target_Override</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.copy_files_target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCopy_Files_Target_Override([NotNull] KotorPatchingLanguageParser.Copy_Files_Target_OverrideContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Copy_Files_Command_KeepName</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.copy_files_command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCopy_Files_Command_KeepName([NotNull] KotorPatchingLanguageParser.Copy_Files_Command_KeepNameContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Copy_Files_Command_ChangeName</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.copy_files_command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCopy_Files_Command_ChangeName([NotNull] KotorPatchingLanguageParser.Copy_Files_Command_ChangeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TwoDAAssignCell</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.twoda_assign_cell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTwoDAAssignCell([NotNull] KotorPatchingLanguageParser.TwoDAAssignCellContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TwoDATargetRow</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.twoda_target_row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTwoDATargetRow([NotNull] KotorPatchingLanguageParser.TwoDATargetRowContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>TwoDACopyRow</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.twoda_copy_row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTwoDACopyRow([NotNull] KotorPatchingLanguageParser.TwoDACopyRowContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KotorPatchingLanguageParser.gff_copy_template"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGff_copy_template([NotNull] KotorPatchingLanguageParser.Gff_copy_templateContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFLocateField</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_locate_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFLocateField([NotNull] KotorPatchingLanguageParser.GFFLocateFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFAssignUInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_assign_uint8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFAssignUInt8([NotNull] KotorPatchingLanguageParser.GFFAssignUInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueUInt8Literal</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_uint8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueUInt8Literal([NotNull] KotorPatchingLanguageParser.GFFValueUInt8LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueUInt8Token</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_uint8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueUInt8Token([NotNull] KotorPatchingLanguageParser.GFFValueUInt8TokenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueUInt8From2DA</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_uint8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueUInt8From2DA([NotNull] KotorPatchingLanguageParser.GFFValueUInt8From2DAContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueUInt8BoolLiteral</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_uint8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueUInt8BoolLiteral([NotNull] KotorPatchingLanguageParser.GFFValueUInt8BoolLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFAssignUInt16</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_assign_uint16"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFAssignUInt16([NotNull] KotorPatchingLanguageParser.GFFAssignUInt16Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueUInt16Literal</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_uint16"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueUInt16Literal([NotNull] KotorPatchingLanguageParser.GFFValueUInt16LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueUInt16Token</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_uint16"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueUInt16Token([NotNull] KotorPatchingLanguageParser.GFFValueUInt16TokenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueUInt16From2DA</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_uint16"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueUInt16From2DA([NotNull] KotorPatchingLanguageParser.GFFValueUInt16From2DAContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFAssignUInt32</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_assign_uint32"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFAssignUInt32([NotNull] KotorPatchingLanguageParser.GFFAssignUInt32Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueUInt32Literal</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_uint32"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueUInt32Literal([NotNull] KotorPatchingLanguageParser.GFFValueUInt32LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueUInt32Token</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_uint32"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueUInt32Token([NotNull] KotorPatchingLanguageParser.GFFValueUInt32TokenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueUInt32From2DA</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_uint32"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueUInt32From2DA([NotNull] KotorPatchingLanguageParser.GFFValueUInt32From2DAContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFAssignUInt64</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_assign_uint64"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFAssignUInt64([NotNull] KotorPatchingLanguageParser.GFFAssignUInt64Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueUInt64Literal</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_uint64"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueUInt64Literal([NotNull] KotorPatchingLanguageParser.GFFValueUInt64LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueUInt64Token</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_uint64"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueUInt64Token([NotNull] KotorPatchingLanguageParser.GFFValueUInt64TokenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueUInt64From2DA</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_uint64"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueUInt64From2DA([NotNull] KotorPatchingLanguageParser.GFFValueUInt64From2DAContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFAssignInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_assign_int8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFAssignInt8([NotNull] KotorPatchingLanguageParser.GFFAssignInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueInt8Literal</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_int8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueInt8Literal([NotNull] KotorPatchingLanguageParser.GFFValueInt8LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueInt8Token</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_int8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueInt8Token([NotNull] KotorPatchingLanguageParser.GFFValueInt8TokenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueInt8From2DA</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_int8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueInt8From2DA([NotNull] KotorPatchingLanguageParser.GFFValueInt8From2DAContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFAssignInt16</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_assign_int16"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFAssignInt16([NotNull] KotorPatchingLanguageParser.GFFAssignInt16Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueInt16Literal</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_int16"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueInt16Literal([NotNull] KotorPatchingLanguageParser.GFFValueInt16LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueInt16Token</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_int16"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueInt16Token([NotNull] KotorPatchingLanguageParser.GFFValueInt16TokenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueInt16From2DA</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_int16"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueInt16From2DA([NotNull] KotorPatchingLanguageParser.GFFValueInt16From2DAContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFAssignInt32</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_assign_int32"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFAssignInt32([NotNull] KotorPatchingLanguageParser.GFFAssignInt32Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueInt32Literal</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_int32"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueInt32Literal([NotNull] KotorPatchingLanguageParser.GFFValueInt32LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueInt32Token</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_int32"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueInt32Token([NotNull] KotorPatchingLanguageParser.GFFValueInt32TokenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueInt32From2DA</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_int32"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueInt32From2DA([NotNull] KotorPatchingLanguageParser.GFFValueInt32From2DAContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFAssignInt64</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_assign_int64"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFAssignInt64([NotNull] KotorPatchingLanguageParser.GFFAssignInt64Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueInt64Literal</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_int64"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueInt64Literal([NotNull] KotorPatchingLanguageParser.GFFValueInt64LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueInt64Token</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_int64"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueInt64Token([NotNull] KotorPatchingLanguageParser.GFFValueInt64TokenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueInt64From2DA</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_int64"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueInt64From2DA([NotNull] KotorPatchingLanguageParser.GFFValueInt64From2DAContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFAssignSingle</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_assign_single"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFAssignSingle([NotNull] KotorPatchingLanguageParser.GFFAssignSingleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueSingleLiteral</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_single"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueSingleLiteral([NotNull] KotorPatchingLanguageParser.GFFValueSingleLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueSingleToken</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_single"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueSingleToken([NotNull] KotorPatchingLanguageParser.GFFValueSingleTokenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueSingleFrom2DA</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_single"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueSingleFrom2DA([NotNull] KotorPatchingLanguageParser.GFFValueSingleFrom2DAContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFAssignDouble</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_assign_double"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFAssignDouble([NotNull] KotorPatchingLanguageParser.GFFAssignDoubleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueDoubleLiteral</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_double"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueDoubleLiteral([NotNull] KotorPatchingLanguageParser.GFFValueDoubleLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueDoubleToken</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_double"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueDoubleToken([NotNull] KotorPatchingLanguageParser.GFFValueDoubleTokenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueDoubleFrom2DA</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_double"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueDoubleFrom2DA([NotNull] KotorPatchingLanguageParser.GFFValueDoubleFrom2DAContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFAssignResRef</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_assign_resref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFAssignResRef([NotNull] KotorPatchingLanguageParser.GFFAssignResRefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueResRefLiteral</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_resref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueResRefLiteral([NotNull] KotorPatchingLanguageParser.GFFValueResRefLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueResRefToken</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_resref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueResRefToken([NotNull] KotorPatchingLanguageParser.GFFValueResRefTokenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueResRefFrom2DA</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_resref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueResRefFrom2DA([NotNull] KotorPatchingLanguageParser.GFFValueResRefFrom2DAContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFAssignString</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_assign_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFAssignString([NotNull] KotorPatchingLanguageParser.GFFAssignStringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueStringLiteral</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueStringLiteral([NotNull] KotorPatchingLanguageParser.GFFValueStringLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueStringToken</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueStringToken([NotNull] KotorPatchingLanguageParser.GFFValueStringTokenContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueStringFrom2DA</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueStringFrom2DA([NotNull] KotorPatchingLanguageParser.GFFValueStringFrom2DAContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFAssignBinary</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_assign_binary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFAssignBinary([NotNull] KotorPatchingLanguageParser.GFFAssignBinaryContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueBinaryBase64</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_binary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueBinaryBase64([NotNull] KotorPatchingLanguageParser.GFFValueBinaryBase64Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFAssignLocalizedStringStringRef</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_assign_locstring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFAssignLocalizedStringStringRef([NotNull] KotorPatchingLanguageParser.GFFAssignLocalizedStringStringRefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueLocalizedString</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_locstring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueLocalizedString([NotNull] KotorPatchingLanguageParser.GFFValueLocalizedStringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValue_LocalizedString_Substrings</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_locstring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValue_LocalizedString_Substrings([NotNull] KotorPatchingLanguageParser.GFFValue_LocalizedString_SubstringsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValue_LocalizedString_MaleEnglish</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_locstring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValue_LocalizedString_MaleEnglish([NotNull] KotorPatchingLanguageParser.GFFValue_LocalizedString_MaleEnglishContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValue_LocalizedString_Substring_LanguageGender</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_locstring_substring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValue_LocalizedString_Substring_LanguageGender([NotNull] KotorPatchingLanguageParser.GFFValue_LocalizedString_Substring_LanguageGenderContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValue_LocalizedString_Substring_Language</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_locstring_substring"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValue_LocalizedString_Substring_Language([NotNull] KotorPatchingLanguageParser.GFFValue_LocalizedString_Substring_LanguageContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFAssignVector3</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_assign_vector3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFAssignVector3([NotNull] KotorPatchingLanguageParser.GFFAssignVector3Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueVector3Literal</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_vector3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueVector3Literal([NotNull] KotorPatchingLanguageParser.GFFValueVector3LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFAssignVector4</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_assign_vector4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFAssignVector4([NotNull] KotorPatchingLanguageParser.GFFAssignVector4Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>GFFValueVector4Literal</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.gff_value_vector4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGFFValueVector4Literal([NotNull] KotorPatchingLanguageParser.GFFValueVector4LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EditCreature</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.edit_creature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEditCreature([NotNull] KotorPatchingLanguageParser.EditCreatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KotorPatchingLanguageParser.edit_creature_mod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEdit_creature_mod([NotNull] KotorPatchingLanguageParser.Edit_creature_modContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_AppearanceType_SetField_Int32</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_appearance_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_AppearanceType_SetField_Int32([NotNull] KotorPatchingLanguageParser.UTC_AppearanceType_SetField_Int32Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_AppearanceType_SetField_2DALabelLookup</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_appearance_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_AppearanceType_SetField_2DALabelLookup([NotNull] KotorPatchingLanguageParser.UTC_AppearanceType_SetField_2DALabelLookupContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_BlindSpot_SetField_Single</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_blind_spot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_BlindSpot_SetField_Single([NotNull] KotorPatchingLanguageParser.UTC_BlindSpot_SetField_SingleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Cha_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_cha"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Cha_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_Cha_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_ChallengeRating_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_challenge_rating"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_ChallengeRating_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_ChallengeRating_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Con_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_con"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Con_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_Con_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Conversation_SetField_ResRef</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_conversation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Conversation_SetField_ResRef([NotNull] KotorPatchingLanguageParser.UTC_Conversation_SetField_ResRefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_CurrentForce_SetField_Int16</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_current_force"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_CurrentForce_SetField_Int16([NotNull] KotorPatchingLanguageParser.UTC_CurrentForce_SetField_Int16Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_CurrentHitPoints_SetField_Int16</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_current_hit_points"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_CurrentHitPoints_SetField_Int16([NotNull] KotorPatchingLanguageParser.UTC_CurrentHitPoints_SetField_Int16Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Description_SetField_LocalizedString</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_description"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Description_SetField_LocalizedString([NotNull] KotorPatchingLanguageParser.UTC_Description_SetField_LocalizedStringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Dex_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_dex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Dex_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_Dex_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Disarmable_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_disarmable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Disarmable_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_Disarmable_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_FactionID_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_faction_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_FactionID_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_FactionID_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_FactionID_SetField_2DALabelLookup</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_faction_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_FactionID_SetField_2DALabelLookup([NotNull] KotorPatchingLanguageParser.UTC_FactionID_SetField_2DALabelLookupContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_FirstName_SetField_LocalizedString</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_first_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_FirstName_SetField_LocalizedString([NotNull] KotorPatchingLanguageParser.UTC_FirstName_SetField_LocalizedStringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_ForcePoints_SetField_Int16</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_force_points"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_ForcePoints_SetField_Int16([NotNull] KotorPatchingLanguageParser.UTC_ForcePoints_SetField_Int16Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Gender_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_gender"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Gender_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_Gender_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_GoodEvil_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_good_evil"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_GoodEvil_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_GoodEvil_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_HitPoints_SetField_Int16</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_hit_points"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_HitPoints_SetField_Int16([NotNull] KotorPatchingLanguageParser.UTC_HitPoints_SetField_Int16Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Hologram_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_hologram"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Hologram_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_Hologram_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_IgnoreCrePath_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_ignore_cre_path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_IgnoreCrePath_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_IgnoreCrePath_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Int_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Int_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_Int_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_IsPC_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_is_pc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_IsPC_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_IsPC_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_LastName_SetField_LocalizedString</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_last_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_LastName_SetField_LocalizedString([NotNull] KotorPatchingLanguageParser.UTC_LastName_SetField_LocalizedStringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_MaxHitPoints_SetField_Int16</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_max_hit_points"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_MaxHitPoints_SetField_Int16([NotNull] KotorPatchingLanguageParser.UTC_MaxHitPoints_SetField_Int16Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Min1HP_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_min_1_hp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Min1HP_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_Min1HP_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_MultiplierSet_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_multiplier_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_MultiplierSet_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_MultiplierSet_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_NaturalAC_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_natural_ac"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_NaturalAC_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_NaturalAC_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_NoPermanentDeath_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_no_perm_death"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_NoPermanentDeath_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_NoPermanentDeath_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_NotReorienting_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_not_reorienting"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_NotReorienting_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_NotReorienting_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_PartInteract_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_party_interact"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_PartInteract_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_PartInteract_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_PerceiptionRange_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_perception_range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_PerceiptionRange_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_PerceiptionRange_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Plot_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_plot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Plot_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_Plot_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Phenotype_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_phenotype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Phenotype_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_Phenotype_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Phenotype_SetField_2DALabelLookup</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_phenotype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Phenotype_SetField_2DALabelLookup([NotNull] KotorPatchingLanguageParser.UTC_Phenotype_SetField_2DALabelLookupContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_PortraitID_SetField_Int32</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_portrait_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_PortraitID_SetField_Int32([NotNull] KotorPatchingLanguageParser.UTC_PortraitID_SetField_Int32Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_PortraitID_SetField_2DALabelLookup</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_portrait_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_PortraitID_SetField_2DALabelLookup([NotNull] KotorPatchingLanguageParser.UTC_PortraitID_SetField_2DALabelLookupContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Race_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_race"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Race_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_Race_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Race_SetField_2DALabelLookup</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_race"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Race_SetField_2DALabelLookup([NotNull] KotorPatchingLanguageParser.UTC_Race_SetField_2DALabelLookupContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_ScriptAttacked_SetField_ResRef</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_script_attacked"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_ScriptAttacked_SetField_ResRef([NotNull] KotorPatchingLanguageParser.UTC_ScriptAttacked_SetField_ResRefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_ScriptDamaged_SetField_ResRef</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_script_damaged"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_ScriptDamaged_SetField_ResRef([NotNull] KotorPatchingLanguageParser.UTC_ScriptDamaged_SetField_ResRefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_ScriptDeath_SetField_ResRef</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_script_death"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_ScriptDeath_SetField_ResRef([NotNull] KotorPatchingLanguageParser.UTC_ScriptDeath_SetField_ResRefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_ScriptDialogue_SetField_ResRef</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_script_dialogue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_ScriptDialogue_SetField_ResRef([NotNull] KotorPatchingLanguageParser.UTC_ScriptDialogue_SetField_ResRefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_ScriptDisturbed_SetField_ResRef</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_script_disturbed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_ScriptDisturbed_SetField_ResRef([NotNull] KotorPatchingLanguageParser.UTC_ScriptDisturbed_SetField_ResRefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_ScriptEndDialog_SetField_ResRef</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_script_end_dialogu"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_ScriptEndDialog_SetField_ResRef([NotNull] KotorPatchingLanguageParser.UTC_ScriptEndDialog_SetField_ResRefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_ScriptEndRound_SetField_ResRef</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_script_end_round"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_ScriptEndRound_SetField_ResRef([NotNull] KotorPatchingLanguageParser.UTC_ScriptEndRound_SetField_ResRefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_ScriptHeartbeat_SetField_ResRef</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_script_heartbeat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_ScriptHeartbeat_SetField_ResRef([NotNull] KotorPatchingLanguageParser.UTC_ScriptHeartbeat_SetField_ResRefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_ScriptBlocked_SetField_ResRef</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_script_on_blocked"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_ScriptBlocked_SetField_ResRef([NotNull] KotorPatchingLanguageParser.UTC_ScriptBlocked_SetField_ResRefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_ScriptNotice_SetField_ResRef</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_script_on_notice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_ScriptNotice_SetField_ResRef([NotNull] KotorPatchingLanguageParser.UTC_ScriptNotice_SetField_ResRefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_ScriptRested_SetField_ResRef</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_script_rested"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_ScriptRested_SetField_ResRef([NotNull] KotorPatchingLanguageParser.UTC_ScriptRested_SetField_ResRefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_ScriptSpawn_SetField_ResRef</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_script_spawn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_ScriptSpawn_SetField_ResRef([NotNull] KotorPatchingLanguageParser.UTC_ScriptSpawn_SetField_ResRefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_ScriptSpellAt_SetField_ResRef</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_script_spell_at"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_ScriptSpellAt_SetField_ResRef([NotNull] KotorPatchingLanguageParser.UTC_ScriptSpellAt_SetField_ResRefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_ScriptUserDefine_SetField_ResRef</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_script_user_define"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_ScriptUserDefine_SetField_ResRef([NotNull] KotorPatchingLanguageParser.UTC_ScriptUserDefine_SetField_ResRefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_SoundsetFile_SetField_UInt16</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_sound_set_file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_SoundsetFile_SetField_UInt16([NotNull] KotorPatchingLanguageParser.UTC_SoundsetFile_SetField_UInt16Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_SoundsetFile_SetField_2DALabelLookup</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_sound_set_file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_SoundsetFile_SetField_2DALabelLookup([NotNull] KotorPatchingLanguageParser.UTC_SoundsetFile_SetField_2DALabelLookupContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Str_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Str_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_Str_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Subrace_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_subrace_index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Subrace_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_Subrace_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Tag_SetField_String</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_tag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Tag_SetField_String([NotNull] KotorPatchingLanguageParser.UTC_Tag_SetField_StringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_WalkRate_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_walk_rate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_WalkRate_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_WalkRate_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_WalkRate_SetField_2DALabelLookup</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_walk_rate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_WalkRate_SetField_2DALabelLookup([NotNull] KotorPatchingLanguageParser.UTC_WalkRate_SetField_2DALabelLookupContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Wis_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_wis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Wis_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_Wis_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_FortBonus_SetField_Int16</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_fortbonus"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_FortBonus_SetField_Int16([NotNull] KotorPatchingLanguageParser.UTC_FortBonus_SetField_Int16Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_RefBonus_SetField_Int16</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_refbonus"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_RefBonus_SetField_Int16([NotNull] KotorPatchingLanguageParser.UTC_RefBonus_SetField_Int16Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_WillBonus_SetField_Int16</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_field_willbonus"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_WillBonus_SetField_Int16([NotNull] KotorPatchingLanguageParser.UTC_WillBonus_SetField_Int16Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Skills_ComputerUse_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_skills_set_field_computer_use"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Skills_ComputerUse_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_Skills_ComputerUse_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Skills_Demolutions_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_skills_set_field_demolitions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Skills_Demolutions_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_Skills_Demolutions_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Skills_Stealth_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_skills_set_field_stealth"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Skills_Stealth_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_Skills_Stealth_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Skills_Awareness_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_skills_set_field_awareness"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Skills_Awareness_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_Skills_Awareness_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Skills_Persuade_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_skills_set_field_persuade"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Skills_Persuade_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_Skills_Persuade_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Skills_Repair_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_skills_set_field_repair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Skills_Repair_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_Skills_Repair_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Skills_Security_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_skills_set_field_security"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Skills_Security_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_Skills_Security_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Skills_TreatInjury_SetField_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_skills_set_field_treat_injury"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Skills_TreatInjury_SetField_UInt8([NotNull] KotorPatchingLanguageParser.UTC_Skills_TreatInjury_SetField_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_AddFeat_UInt16</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_add_feat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_AddFeat_UInt16([NotNull] KotorPatchingLanguageParser.UTC_AddFeat_UInt16Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_AddFeat_2DALabelLookup</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_add_feat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_AddFeat_2DALabelLookup([NotNull] KotorPatchingLanguageParser.UTC_AddFeat_2DALabelLookupContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Class_SetNew</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Class_SetNew([NotNull] KotorPatchingLanguageParser.UTC_Class_SetNewContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Class_SetFirst</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Class_SetFirst([NotNull] KotorPatchingLanguageParser.UTC_Class_SetFirstContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Class_SetSecond</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Class_SetSecond([NotNull] KotorPatchingLanguageParser.UTC_Class_SetSecondContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KotorPatchingLanguageParser.utc_class_mod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUtc_class_mod([NotNull] KotorPatchingLanguageParser.Utc_class_modContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Class_AddPower_UInt16</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_class_add_power"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Class_AddPower_UInt16([NotNull] KotorPatchingLanguageParser.UTC_Class_AddPower_UInt16Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Class_AddPower_UInt16_2DALabelLookup</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_class_add_power"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Class_AddPower_UInt16_2DALabelLookup([NotNull] KotorPatchingLanguageParser.UTC_Class_AddPower_UInt16_2DALabelLookupContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Class_Type_SetField_Int32</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_class_type_set_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Class_Type_SetField_Int32([NotNull] KotorPatchingLanguageParser.UTC_Class_Type_SetField_Int32Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Class_Type_SetField_2DALookup</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_class_type_set_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Class_Type_SetField_2DALookup([NotNull] KotorPatchingLanguageParser.UTC_Class_Type_SetField_2DALookupContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_Class_Level_SetField_Int16</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_class_level_set_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_Class_Level_SetField_Int16([NotNull] KotorPatchingLanguageParser.UTC_Class_Level_SetField_Int16Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_AddItem</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_add_inventory"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_AddItem([NotNull] KotorPatchingLanguageParser.UTC_AddItemContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_AddItem_SetField_ResRef</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_add_inventory_mod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_AddItem_SetField_ResRef([NotNull] KotorPatchingLanguageParser.UTC_AddItem_SetField_ResRefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_AddItem_SetField_Dropable</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_add_inventory_mod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_AddItem_SetField_Dropable([NotNull] KotorPatchingLanguageParser.UTC_AddItem_SetField_DropableContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_SetEquipment</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_equipment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_SetEquipment([NotNull] KotorPatchingLanguageParser.UTC_SetEquipmentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_SetEquipment_ResRef_ResRef</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_equipment_mod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_SetEquipment_ResRef_ResRef([NotNull] KotorPatchingLanguageParser.UTC_SetEquipment_ResRef_ResRefContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTC_SetEquipment_Dropable_UInt8</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.utc_set_equipment_mod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTC_SetEquipment_Dropable_UInt8([NotNull] KotorPatchingLanguageParser.UTC_SetEquipment_Dropable_UInt8Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EquipmentSlot_Implant</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.equipment_slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquipmentSlot_Implant([NotNull] KotorPatchingLanguageParser.EquipmentSlot_ImplantContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EquipmentSlot_LeftUtility</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.equipment_slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquipmentSlot_LeftUtility([NotNull] KotorPatchingLanguageParser.EquipmentSlot_LeftUtilityContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EquipmentSlot_Head</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.equipment_slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquipmentSlot_Head([NotNull] KotorPatchingLanguageParser.EquipmentSlot_HeadContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EquipmentSlot_Sensor</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.equipment_slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquipmentSlot_Sensor([NotNull] KotorPatchingLanguageParser.EquipmentSlot_SensorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EquipmentSlot_Hands</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.equipment_slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquipmentSlot_Hands([NotNull] KotorPatchingLanguageParser.EquipmentSlot_HandsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EquipmentSlot_RightUtility</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.equipment_slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquipmentSlot_RightUtility([NotNull] KotorPatchingLanguageParser.EquipmentSlot_RightUtilityContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EquipmentSlot_LeftArm</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.equipment_slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquipmentSlot_LeftArm([NotNull] KotorPatchingLanguageParser.EquipmentSlot_LeftArmContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EquipmentSlot_LeftSpecialWeapon</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.equipment_slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquipmentSlot_LeftSpecialWeapon([NotNull] KotorPatchingLanguageParser.EquipmentSlot_LeftSpecialWeaponContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EquipmentSlot_Body</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.equipment_slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquipmentSlot_Body([NotNull] KotorPatchingLanguageParser.EquipmentSlot_BodyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EquipmentSlot_Plating</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.equipment_slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquipmentSlot_Plating([NotNull] KotorPatchingLanguageParser.EquipmentSlot_PlatingContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EquipmentSlot_RightArm</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.equipment_slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquipmentSlot_RightArm([NotNull] KotorPatchingLanguageParser.EquipmentSlot_RightArmContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EquipmentSlot_RightSpecialWeapon</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.equipment_slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquipmentSlot_RightSpecialWeapon([NotNull] KotorPatchingLanguageParser.EquipmentSlot_RightSpecialWeaponContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EquipmentSlot_LeftWeapon</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.equipment_slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquipmentSlot_LeftWeapon([NotNull] KotorPatchingLanguageParser.EquipmentSlot_LeftWeaponContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EquipmentSlot_Belt</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.equipment_slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquipmentSlot_Belt([NotNull] KotorPatchingLanguageParser.EquipmentSlot_BeltContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EquipmentSlot_Shield</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.equipment_slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquipmentSlot_Shield([NotNull] KotorPatchingLanguageParser.EquipmentSlot_ShieldContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EquipmentSlot_RightWeapon</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.equipment_slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquipmentSlot_RightWeapon([NotNull] KotorPatchingLanguageParser.EquipmentSlot_RightWeaponContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EquipmentSlot_FirstClaw</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.equipment_slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquipmentSlot_FirstClaw([NotNull] KotorPatchingLanguageParser.EquipmentSlot_FirstClawContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EquipmentSlot_SecondClaw</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.equipment_slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquipmentSlot_SecondClaw([NotNull] KotorPatchingLanguageParser.EquipmentSlot_SecondClawContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EquipmentSlot_ThirdClaw</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.equipment_slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquipmentSlot_ThirdClaw([NotNull] KotorPatchingLanguageParser.EquipmentSlot_ThirdClawContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EquipmentSlot_Hide</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.equipment_slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquipmentSlot_Hide([NotNull] KotorPatchingLanguageParser.EquipmentSlot_HideContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EquipmentSlot_AltLeftWeapon</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.equipment_slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquipmentSlot_AltLeftWeapon([NotNull] KotorPatchingLanguageParser.EquipmentSlot_AltLeftWeaponContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EquipmentSlot_AltRight_Weapon</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.equipment_slot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquipmentSlot_AltRight_Weapon([NotNull] KotorPatchingLanguageParser.EquipmentSlot_AltRight_WeaponContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EditItem</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.edit_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEditItem([NotNull] KotorPatchingLanguageParser.EditItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KotorPatchingLanguageParser.edit_item_mod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEdit_item_mod([NotNull] KotorPatchingLanguageParser.Edit_item_modContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTI_BaseItem_SetField_GFFValue</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.uti_set_field_base_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTI_BaseItem_SetField_GFFValue([NotNull] KotorPatchingLanguageParser.UTI_BaseItem_SetField_GFFValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTI_BaseItem_SetField_2DALabelLookup</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.uti_set_field_base_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTI_BaseItem_SetField_2DALabelLookup([NotNull] KotorPatchingLanguageParser.UTI_BaseItem_SetField_2DALabelLookupContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTI_LocalizedName_SetField_GFFValue</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.uti_set_field_localized_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTI_LocalizedName_SetField_GFFValue([NotNull] KotorPatchingLanguageParser.UTI_LocalizedName_SetField_GFFValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTI_Description_SetField_GFFValue</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.uti_set_field_description"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTI_Description_SetField_GFFValue([NotNull] KotorPatchingLanguageParser.UTI_Description_SetField_GFFValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTI_Tag_SetField_GFFValue</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.uti_set_field_tag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTI_Tag_SetField_GFFValue([NotNull] KotorPatchingLanguageParser.UTI_Tag_SetField_GFFValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTI_Charges_SetField_GFFValue</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.uti_set_field_charges"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTI_Charges_SetField_GFFValue([NotNull] KotorPatchingLanguageParser.UTI_Charges_SetField_GFFValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTI_MaxCharges_SetField_GFFValue</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.uti_set_field_max_charges"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTI_MaxCharges_SetField_GFFValue([NotNull] KotorPatchingLanguageParser.UTI_MaxCharges_SetField_GFFValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTI_Cost_SetField_GFFValue</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.uti_set_field_cost"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTI_Cost_SetField_GFFValue([NotNull] KotorPatchingLanguageParser.UTI_Cost_SetField_GFFValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTI_StackSize_SetField_GFFValue</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.uti_set_field_stack_size"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTI_StackSize_SetField_GFFValue([NotNull] KotorPatchingLanguageParser.UTI_StackSize_SetField_GFFValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTI_Plot_SetField_GFFValue</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.uti_set_field_plot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTI_Plot_SetField_GFFValue([NotNull] KotorPatchingLanguageParser.UTI_Plot_SetField_GFFValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTI_Plot_SetField_Bool</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.uti_set_field_plot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTI_Plot_SetField_Bool([NotNull] KotorPatchingLanguageParser.UTI_Plot_SetField_BoolContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTI_ModelVariation_SetField_GFFValue</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.uti_set_field_model_variation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTI_ModelVariation_SetField_GFFValue([NotNull] KotorPatchingLanguageParser.UTI_ModelVariation_SetField_GFFValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTI_TextureVariation_SetField_GFFValue</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.uti_set_field_texture_variation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTI_TextureVariation_SetField_GFFValue([NotNull] KotorPatchingLanguageParser.UTI_TextureVariation_SetField_GFFValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTI_AddProperties</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.uti_add_property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTI_AddProperties([NotNull] KotorPatchingLanguageParser.UTI_AddPropertiesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KotorPatchingLanguageParser.uti_property_mod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUti_property_mod([NotNull] KotorPatchingLanguageParser.Uti_property_modContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTI_Property_PropertyName_SetField_GFFValue</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.uti_property_set_field_property_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTI_Property_PropertyName_SetField_GFFValue([NotNull] KotorPatchingLanguageParser.UTI_Property_PropertyName_SetField_GFFValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTI_Property_SubType_SetField_GFFValue</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.uti_property_set_field_subtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTI_Property_SubType_SetField_GFFValue([NotNull] KotorPatchingLanguageParser.UTI_Property_SubType_SetField_GFFValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTI_Property_ChanceAppear_SetField_GFFValue</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.uti_property_set_field_chance_appear"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTI_Property_ChanceAppear_SetField_GFFValue([NotNull] KotorPatchingLanguageParser.UTI_Property_ChanceAppear_SetField_GFFValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTI_Property_CostTable_SetField_GFFValue</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.uti_property_set_field_cost_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTI_Property_CostTable_SetField_GFFValue([NotNull] KotorPatchingLanguageParser.UTI_Property_CostTable_SetField_GFFValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTI_Property_CostValue_SetField_GFFValue</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.uti_property_set_field_cost_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTI_Property_CostValue_SetField_GFFValue([NotNull] KotorPatchingLanguageParser.UTI_Property_CostValue_SetField_GFFValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTI_Property_Param1_SetField_GFFValue</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.uti_property_set_field_param1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTI_Property_Param1_SetField_GFFValue([NotNull] KotorPatchingLanguageParser.UTI_Property_Param1_SetField_GFFValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTI_Property_Param1Value_SetField_GFFValue</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.uti_property_set_field_param1_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTI_Property_Param1Value_SetField_GFFValue([NotNull] KotorPatchingLanguageParser.UTI_Property_Param1Value_SetField_GFFValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UTI_Property_UpgradeType_SetField_GFFValue</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.uti_property_set_field_upgrade_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUTI_Property_UpgradeType_SetField_GFFValue([NotNull] KotorPatchingLanguageParser.UTI_Property_UpgradeType_SetField_GFFValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EditAppearance</c>
	/// labeled alternative in <see cref="KotorPatchingLanguageParser.edit_appearance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEditAppearance([NotNull] KotorPatchingLanguageParser.EditAppearanceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KotorPatchingLanguageParser.edit_appearance_mod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEdit_appearance_mod([NotNull] KotorPatchingLanguageParser.Edit_appearance_modContext context);
}
