//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/hugin/source/repos/Kotor.NET/Kotor.NET.PatchingLanguage/KotorPatchingLanguage.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class KotorPatchingLanguageParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, STRING_LITERAL=16, 
		INT_LITERAL=17, FLOAT_LITERAL=18, BOOL_LITERAL=19, IDENTIFIER=20, WHITESPACE=21;
	public const int
		RULE_script = 0, RULE_instruction = 1, RULE_twoda_assign_cell = 2, RULE_twoda_target_row = 3, 
		RULE_twoda_copy_row = 4, RULE_gff_copy_template = 5, RULE_edit_appearance = 6, 
		RULE_edit_appearance_mod = 7, RULE_edit_creature = 8, RULE_edit_creature_mod = 9, 
		RULE_edit_creature_field_appearance = 10;
	public static readonly string[] ruleNames = {
		"script", "instruction", "twoda_assign_cell", "twoda_target_row", "twoda_copy_row", 
		"gff_copy_template", "edit_appearance", "edit_appearance_mod", "edit_creature", 
		"edit_creature_mod", "edit_creature_field_appearance"
	};

	private static readonly string[] _LiteralNames = {
		null, "'assign'", "'cell'", "'set'", "'to'", "'target'", "'row'", "'where'", 
		"'is'", "'copy'", "'from'", "'template'", "'edit'", "'appearance'", "'end'", 
		"'creature'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, "STRING_LITERAL", "INT_LITERAL", "FLOAT_LITERAL", 
		"BOOL_LITERAL", "IDENTIFIER", "WHITESPACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "KotorPatchingLanguage.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static KotorPatchingLanguageParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public KotorPatchingLanguageParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public KotorPatchingLanguageParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ScriptContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(KotorPatchingLanguageParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public InstructionContext[] instruction() {
			return GetRuleContexts<InstructionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public InstructionContext instruction(int i) {
			return GetRuleContext<InstructionContext>(i);
		}
		public ScriptContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_script; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKotorPatchingLanguageVisitor<TResult> typedVisitor = visitor as IKotorPatchingLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitScript(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ScriptContext script() {
		ScriptContext _localctx = new ScriptContext(Context, State);
		EnterRule(_localctx, 0, RULE_script);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 25;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__11) {
				{
				{
				State = 22;
				instruction();
				}
				}
				State = 27;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 28;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InstructionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Edit_appearanceContext edit_appearance() {
			return GetRuleContext<Edit_appearanceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Edit_creatureContext edit_creature() {
			return GetRuleContext<Edit_creatureContext>(0);
		}
		public InstructionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instruction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKotorPatchingLanguageVisitor<TResult> typedVisitor = visitor as IKotorPatchingLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInstruction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public InstructionContext instruction() {
		InstructionContext _localctx = new InstructionContext(Context, State);
		EnterRule(_localctx, 2, RULE_instruction);
		try {
			State = 32;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 30;
				edit_appearance();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 31;
				edit_creature();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Twoda_assign_cellContext : ParserRuleContext {
		public Twoda_assign_cellContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_twoda_assign_cell; } }
	 
		public Twoda_assign_cellContext() { }
		public virtual void CopyFrom(Twoda_assign_cellContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class TwoDAAssignCellContext : Twoda_assign_cellContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] STRING_LITERAL() { return GetTokens(KotorPatchingLanguageParser.STRING_LITERAL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_LITERAL(int i) {
			return GetToken(KotorPatchingLanguageParser.STRING_LITERAL, i);
		}
		public TwoDAAssignCellContext(Twoda_assign_cellContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKotorPatchingLanguageVisitor<TResult> typedVisitor = visitor as IKotorPatchingLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTwoDAAssignCell(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Twoda_assign_cellContext twoda_assign_cell() {
		Twoda_assign_cellContext _localctx = new Twoda_assign_cellContext(Context, State);
		EnterRule(_localctx, 4, RULE_twoda_assign_cell);
		try {
			_localctx = new TwoDAAssignCellContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 34;
			Match(T__0);
			State = 35;
			Match(T__1);
			State = 36;
			Match(T__2);
			State = 37;
			Match(STRING_LITERAL);
			State = 38;
			Match(T__3);
			State = 39;
			Match(STRING_LITERAL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Twoda_target_rowContext : ParserRuleContext {
		public Twoda_target_rowContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_twoda_target_row; } }
	 
		public Twoda_target_rowContext() { }
		public virtual void CopyFrom(Twoda_target_rowContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class TwoDATargetRowContext : Twoda_target_rowContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] STRING_LITERAL() { return GetTokens(KotorPatchingLanguageParser.STRING_LITERAL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_LITERAL(int i) {
			return GetToken(KotorPatchingLanguageParser.STRING_LITERAL, i);
		}
		public TwoDATargetRowContext(Twoda_target_rowContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKotorPatchingLanguageVisitor<TResult> typedVisitor = visitor as IKotorPatchingLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTwoDATargetRow(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Twoda_target_rowContext twoda_target_row() {
		Twoda_target_rowContext _localctx = new Twoda_target_rowContext(Context, State);
		EnterRule(_localctx, 6, RULE_twoda_target_row);
		try {
			_localctx = new TwoDATargetRowContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 41;
			Match(T__4);
			State = 42;
			Match(T__5);
			State = 43;
			Match(T__6);
			State = 44;
			Match(STRING_LITERAL);
			State = 45;
			Match(T__7);
			State = 46;
			Match(STRING_LITERAL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Twoda_copy_rowContext : ParserRuleContext {
		public Twoda_copy_rowContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_twoda_copy_row; } }
	 
		public Twoda_copy_rowContext() { }
		public virtual void CopyFrom(Twoda_copy_rowContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class TwoDACopyRowContext : Twoda_copy_rowContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] STRING_LITERAL() { return GetTokens(KotorPatchingLanguageParser.STRING_LITERAL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_LITERAL(int i) {
			return GetToken(KotorPatchingLanguageParser.STRING_LITERAL, i);
		}
		public TwoDACopyRowContext(Twoda_copy_rowContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKotorPatchingLanguageVisitor<TResult> typedVisitor = visitor as IKotorPatchingLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTwoDACopyRow(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Twoda_copy_rowContext twoda_copy_row() {
		Twoda_copy_rowContext _localctx = new Twoda_copy_rowContext(Context, State);
		EnterRule(_localctx, 8, RULE_twoda_copy_row);
		try {
			_localctx = new TwoDACopyRowContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 48;
			Match(T__8);
			State = 49;
			Match(T__5);
			State = 50;
			Match(T__6);
			State = 51;
			Match(STRING_LITERAL);
			State = 52;
			Match(T__7);
			State = 53;
			Match(STRING_LITERAL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Gff_copy_templateContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_LITERAL() { return GetToken(KotorPatchingLanguageParser.STRING_LITERAL, 0); }
		public Gff_copy_templateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_gff_copy_template; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKotorPatchingLanguageVisitor<TResult> typedVisitor = visitor as IKotorPatchingLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGff_copy_template(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Gff_copy_templateContext gff_copy_template() {
		Gff_copy_templateContext _localctx = new Gff_copy_templateContext(Context, State);
		EnterRule(_localctx, 10, RULE_gff_copy_template);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 55;
			Match(T__8);
			State = 56;
			Match(T__9);
			State = 57;
			Match(T__10);
			State = 58;
			Match(STRING_LITERAL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Edit_appearanceContext : ParserRuleContext {
		public Edit_appearanceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_edit_appearance; } }
	 
		public Edit_appearanceContext() { }
		public virtual void CopyFrom(Edit_appearanceContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class EditAppearanceContext : Edit_appearanceContext {
		[System.Diagnostics.DebuggerNonUserCode] public Edit_appearance_modContext[] edit_appearance_mod() {
			return GetRuleContexts<Edit_appearance_modContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Edit_appearance_modContext edit_appearance_mod(int i) {
			return GetRuleContext<Edit_appearance_modContext>(i);
		}
		public EditAppearanceContext(Edit_appearanceContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKotorPatchingLanguageVisitor<TResult> typedVisitor = visitor as IKotorPatchingLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEditAppearance(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Edit_appearanceContext edit_appearance() {
		Edit_appearanceContext _localctx = new Edit_appearanceContext(Context, State);
		EnterRule(_localctx, 12, RULE_edit_appearance);
		int _la;
		try {
			_localctx = new EditAppearanceContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 60;
			Match(T__11);
			State = 61;
			Match(T__12);
			State = 65;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 546L) != 0)) {
				{
				{
				State = 62;
				edit_appearance_mod();
				}
				}
				State = 67;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 68;
			Match(T__13);
			State = 69;
			Match(T__11);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Edit_appearance_modContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Twoda_target_rowContext twoda_target_row() {
			return GetRuleContext<Twoda_target_rowContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Twoda_copy_rowContext twoda_copy_row() {
			return GetRuleContext<Twoda_copy_rowContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Twoda_assign_cellContext twoda_assign_cell() {
			return GetRuleContext<Twoda_assign_cellContext>(0);
		}
		public Edit_appearance_modContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_edit_appearance_mod; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKotorPatchingLanguageVisitor<TResult> typedVisitor = visitor as IKotorPatchingLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEdit_appearance_mod(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Edit_appearance_modContext edit_appearance_mod() {
		Edit_appearance_modContext _localctx = new Edit_appearance_modContext(Context, State);
		EnterRule(_localctx, 14, RULE_edit_appearance_mod);
		try {
			State = 74;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__4:
				EnterOuterAlt(_localctx, 1);
				{
				State = 71;
				twoda_target_row();
				}
				break;
			case T__8:
				EnterOuterAlt(_localctx, 2);
				{
				State = 72;
				twoda_copy_row();
				}
				break;
			case T__0:
				EnterOuterAlt(_localctx, 3);
				{
				State = 73;
				twoda_assign_cell();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Edit_creatureContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_LITERAL() { return GetToken(KotorPatchingLanguageParser.STRING_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Edit_creature_modContext[] edit_creature_mod() {
			return GetRuleContexts<Edit_creature_modContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Edit_creature_modContext edit_creature_mod(int i) {
			return GetRuleContext<Edit_creature_modContext>(i);
		}
		public Edit_creatureContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_edit_creature; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKotorPatchingLanguageVisitor<TResult> typedVisitor = visitor as IKotorPatchingLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEdit_creature(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Edit_creatureContext edit_creature() {
		Edit_creatureContext _localctx = new Edit_creatureContext(Context, State);
		EnterRule(_localctx, 16, RULE_edit_creature);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 76;
			Match(T__11);
			State = 77;
			Match(T__14);
			State = 78;
			Match(STRING_LITERAL);
			State = 82;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__2 || _la==T__8) {
				{
				{
				State = 79;
				edit_creature_mod();
				}
				}
				State = 84;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 85;
			Match(T__13);
			State = 86;
			Match(T__11);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Edit_creature_modContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Gff_copy_templateContext gff_copy_template() {
			return GetRuleContext<Gff_copy_templateContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Edit_creature_field_appearanceContext edit_creature_field_appearance() {
			return GetRuleContext<Edit_creature_field_appearanceContext>(0);
		}
		public Edit_creature_modContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_edit_creature_mod; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKotorPatchingLanguageVisitor<TResult> typedVisitor = visitor as IKotorPatchingLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEdit_creature_mod(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Edit_creature_modContext edit_creature_mod() {
		Edit_creature_modContext _localctx = new Edit_creature_modContext(Context, State);
		EnterRule(_localctx, 18, RULE_edit_creature_mod);
		try {
			State = 90;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__8:
				EnterOuterAlt(_localctx, 1);
				{
				State = 88;
				gff_copy_template();
				}
				break;
			case T__2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 89;
				edit_creature_field_appearance();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Edit_creature_field_appearanceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT_LITERAL() { return GetToken(KotorPatchingLanguageParser.INT_LITERAL, 0); }
		public Edit_creature_field_appearanceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_edit_creature_field_appearance; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKotorPatchingLanguageVisitor<TResult> typedVisitor = visitor as IKotorPatchingLanguageVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEdit_creature_field_appearance(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Edit_creature_field_appearanceContext edit_creature_field_appearance() {
		Edit_creature_field_appearanceContext _localctx = new Edit_creature_field_appearanceContext(Context, State);
		EnterRule(_localctx, 20, RULE_edit_creature_field_appearance);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 92;
			Match(T__2);
			State = 93;
			Match(T__12);
			State = 94;
			Match(INT_LITERAL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,21,97,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,1,0,5,0,24,8,0,10,0,12,0,27,9,0,1,0,1,0,
		1,1,1,1,3,1,33,8,1,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,3,1,3,1,3,1,3,1,3,1,3,
		1,3,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,5,1,5,1,5,1,5,1,5,1,6,1,6,1,6,5,6,64,
		8,6,10,6,12,6,67,9,6,1,6,1,6,1,6,1,7,1,7,1,7,3,7,75,8,7,1,8,1,8,1,8,1,
		8,5,8,81,8,8,10,8,12,8,84,9,8,1,8,1,8,1,8,1,9,1,9,3,9,91,8,9,1,10,1,10,
		1,10,1,10,1,10,0,0,11,0,2,4,6,8,10,12,14,16,18,20,0,0,92,0,25,1,0,0,0,
		2,32,1,0,0,0,4,34,1,0,0,0,6,41,1,0,0,0,8,48,1,0,0,0,10,55,1,0,0,0,12,60,
		1,0,0,0,14,74,1,0,0,0,16,76,1,0,0,0,18,90,1,0,0,0,20,92,1,0,0,0,22,24,
		3,2,1,0,23,22,1,0,0,0,24,27,1,0,0,0,25,23,1,0,0,0,25,26,1,0,0,0,26,28,
		1,0,0,0,27,25,1,0,0,0,28,29,5,0,0,1,29,1,1,0,0,0,30,33,3,12,6,0,31,33,
		3,16,8,0,32,30,1,0,0,0,32,31,1,0,0,0,33,3,1,0,0,0,34,35,5,1,0,0,35,36,
		5,2,0,0,36,37,5,3,0,0,37,38,5,16,0,0,38,39,5,4,0,0,39,40,5,16,0,0,40,5,
		1,0,0,0,41,42,5,5,0,0,42,43,5,6,0,0,43,44,5,7,0,0,44,45,5,16,0,0,45,46,
		5,8,0,0,46,47,5,16,0,0,47,7,1,0,0,0,48,49,5,9,0,0,49,50,5,6,0,0,50,51,
		5,7,0,0,51,52,5,16,0,0,52,53,5,8,0,0,53,54,5,16,0,0,54,9,1,0,0,0,55,56,
		5,9,0,0,56,57,5,10,0,0,57,58,5,11,0,0,58,59,5,16,0,0,59,11,1,0,0,0,60,
		61,5,12,0,0,61,65,5,13,0,0,62,64,3,14,7,0,63,62,1,0,0,0,64,67,1,0,0,0,
		65,63,1,0,0,0,65,66,1,0,0,0,66,68,1,0,0,0,67,65,1,0,0,0,68,69,5,14,0,0,
		69,70,5,12,0,0,70,13,1,0,0,0,71,75,3,6,3,0,72,75,3,8,4,0,73,75,3,4,2,0,
		74,71,1,0,0,0,74,72,1,0,0,0,74,73,1,0,0,0,75,15,1,0,0,0,76,77,5,12,0,0,
		77,78,5,15,0,0,78,82,5,16,0,0,79,81,3,18,9,0,80,79,1,0,0,0,81,84,1,0,0,
		0,82,80,1,0,0,0,82,83,1,0,0,0,83,85,1,0,0,0,84,82,1,0,0,0,85,86,5,14,0,
		0,86,87,5,12,0,0,87,17,1,0,0,0,88,91,3,10,5,0,89,91,3,20,10,0,90,88,1,
		0,0,0,90,89,1,0,0,0,91,19,1,0,0,0,92,93,5,3,0,0,93,94,5,13,0,0,94,95,5,
		17,0,0,95,21,1,0,0,0,6,25,32,65,74,82,90
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
